apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: docker-registry-browser
  name: docker-registry-browser-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: docker-browser
    app.kubernetes.io/name: docker-registry-browser
  type: LoadBalancer
  loadBalancerIP: 192.168.0.65
