apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresses
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.50-192.168.0.100

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-addresses
