apiVersion: v1
kind: Service
metadata:
  name: docker-reg-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.50
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
