apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stump
  name: stump
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stump
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stump
    spec:
      initContainers:
      - name: fix-perms
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
        - name: stump-cfg
          mountPath: /config
      containers:
      - image: aaronleopold/stump:latest
        name: stump
        ports:
        - containerPort: 10801
        env:
        - name: STUMP_ENABLE_UPLOAD
          value: "true"
        - name: STUMP_CONFIG_DIR
          value: "/config"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        resources: {}
        volumeMounts:
        - name: stump-cfg
          mountPath: /config
        - name: stump-media
          mountPath: /data

      volumes:
      - name: stump-cfg
        persistentVolumeClaim:
          claimName: stump-cfg
      - name: stump-media
        persistentVolumeClaim:
          claimName: stump-media
status: {}
