env:
  - name: REGISTRY_URL
    valueFrom:
      secretKeyRef:
        name: registry-ui-secret
        key: url
  - name: REGISTRY_AUTH
    valueFrom:
      secretKeyRef:
        name: registry-ui-secret
        key: auth

image:
  repository: "public-registry.brunobernard.dev/docker-registry-ui"
  pullPolicy: Always
  tag: "1.0.0-alpha.1"
