apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-postgres
  namespace: cnpg
spec:
  instances: 3
  storage:
    size: 15Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-objectstore

  postgresql:
    parameters:
      max_slot_wal_keep_size: "5GB"

  managed:
    roles:
      # Application 1: GoToSocial
      - name: gotosocial
        login: true
        passwordSecret:
          name: gotosocial-db-password

      # Application 2: KRaft
      # - name: kraft
      #   login: true
      #   passwordSecret:
      #     name: kraft-db-password

  # bootstrap:
  #   initdb:
  #     database: default
  #     owner: root
  #     secret:
  #       name: root-user-secret
  #     postInitSQL:
  #       - CREATE DATABASE gotosocial OWNER gotosocial;
  #       - CREATE DATABASE mastodon OWNER mastodon;
  #       - CREATE DATABASE immich OWNER immich;
  #   recovery:
  #     source: source

  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: cnpg-main
        serverName: cnpg-main
