apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-postgres
  namespace: cnpg
spec:
  instances: 1
  storage:
    size: 10Gi

  managed:
    roles:
      # Application 1: GoToSocial
      - name: gotosocial
        login: true
        passwordSecret:
          name: gotosocial-db-password

      # Application 2: KRaft
      # - name: kraft
      #   login: true
      #   passwordSecret:
      #     name: kraft-db-password

  bootstrap:
    initdb:
      database: default
      owner: root
      secret:
        name: root-user-secret
      postInitSQL:
        - CREATE DATABASE gotosocial OWNER gotosocial;
      #   - CREATE DATABASE mastodon OWNER mastodon;
      #   - CREATE DATABASE immich OWNER immich;
