apiVersion: v1
kind: Secret
metadata:
  name: root-user-secret
  namespace: cnpg
type: Opaque
stringData:
  password: "rootpassword"

---

apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-db-password
  namespace: cnpg
type: Opaque
stringData:
  DB_DATABASE_NAME: gotosocial
  username: gotosocial
  password: "password"

---

apiVersion: v1
kind: Secret
metadata:
  name: kraft-db-password
  namespace: cnpg
type: Opaque
stringData:
  password: "password"
