apiVersion: apps/v1
kind: Deployment
metadata:
  name: continuwuity
  labels:
    app: continuwuity
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: continuwuity
  template:
    metadata:
      labels:
        app: continuwuity
    spec:
      containers:
      - name: continuwuity
        image: forgejo.ellis.link/continuwuation/continuwuity:latest
        ports:
        - containerPort: 6167

        resources:
          requests:
            cpu: 10m
            memory: 300M

        env:
        - name: CONDUWUIT_CONFIG
          value: "/config/continuwuity.toml"

        volumeMounts:
        - name: db-storage
          mountPath: /data
        - name: db-backup
          mountPath: /backups
        - name: continuwuity-config
          readOnly: true
          mountPath: /config
          # subPath: continuwuity.toml

      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: continuwuity-db-pvc
      - name: db-backup
        persistentVolumeClaim:
          claimName: continuwuity-backup-pvc
      - name: continuwuity-config
        configMap:
          name: continuwuity
