apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudnativemu-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: issuer
spec:
  tls:
    - hosts:
        - cnmu.alexbissessur.dev
      secretName: tls-cnmu-ingress
  rules:
  - host: cnmu.alexbissessur.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudnativemu
            port: 
              number: 8000

