apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configmap
data:
  Caddyfile: |
    registry.alexbissessur.dev {
      reverse_proxy localhost:5000
      tls
    }
    test.alexbissessur.dev {
      respond "Test Works"
      tls
    }
