apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      strategy:
        type: Recreate
      containers:
      - name: caddy
        image: caddy:latest
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy
        - name: caddy-data
          mountPath: /data
        - name: caddy-srv
          mountPath: /srv
        resources:
          requests:
            cpu: 50m
            memory: 50Mi

      volumes:
        - name: caddy-config
          configMap:
            name: caddy-configmap
        - name: caddy-data
          persistentVolumeClaim:
            claimName: caddy-data
        - name: caddy-srv
          persistentVolumeClaim:
            claimName: caddy-srv
