apiVersion: v1
kind: Service
metadata:
  name: caddy-service
  namespace: caddy
spec:
  loadBalancerIP: 192.168.0.54
  selector:
    app: caddy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
