apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  namespace: immich
spec:
  restartPolicy: Never
  containers:
    - name: psql
      image: postgres:15
      command: ["sleep", "infinity"]
