apiVersion: v1
kind: ConfigMap
metadata:
  name: conduit-config
data:
  SERVER_NAME: "matrix.meetup.mu"
  conduit.toml: |
    [global]
    server_name = "matrix.meetup.mu"
    database_backend = "rocksdb"
    database_path = "/var/lib/matrix-conduit/"
    address = "0.0.0.0"
    port = 6167
    # Registration settings
    allow_registration = true
    allow_federation = true
    allow_check_for_updates = false
