apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: conduit-database-pvc

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
