apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-surveillance
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  diskSelector: surveillance
  fromBackup: ""
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

