apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    # covering my ass here
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    # and here
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
