controllers:
  gts:
    replicas: 1
    type: deployment
    pod:
      securityContext:
        fsGroup: 568
    containers:
      gts:
        image:
          repository: docker.io/superseriousbusiness/gotosocial
          tag: "0.21.2"
        env:
          TZ: Indian/Mauritius
          GTS_HOST: gts.alexbissessur.dev
          GTS_ACCOUNT_DOMAIN: alexbissessur.dev
          GTS_ADVANCED_RATE_LIMIT_REQUESTS: 0
          GTS_STORAGE_LOCAL_BASE_PATH: /storage
          GTS_SEMAPHORE_URL: https://phanpy.alexbissessur.dev
          GTS_LANDING_PAGE_USER: "AlexB"
          GTS_DB_TYPE: postgres
          GTS_DB_POSTGRES_CONNECTION_STRING:
            valueFrom:
              secretKeyRef:
                name: database-gotosocial-user
                key: POSTGRES_URL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 1024Mi

persistence:
  storage:
    existingClaim: gotosocial-data

service:
  main:
    controller: gts
    ports:
      http:
        port: 8080
