apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik-metrics
  name: traefik-metrics
  namespace: kube-system
spec:
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
    name: metrics
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  type: ClusterIP
status:
  loadBalancer: {}
