apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.71.0
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/ghost/content

          env:
            - name: database__client
              value: mysql
            - name: database__connection__host
              value: mysql-service
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: ghostdbsecrets
                  key: MYSQL_USER
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghostdbsecrets
                  key: MYSQL_PASSWORD
            - name: database__connection__database
              value: "ghostdb"
            - name: database__connection__port
              value: "3306"
            - name: url
              value: "https://alexbissessur.dev"

      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: ghost-data

---
apiVersion: v1
kind: Service
metadata:
  name: ghost-svc
  namespace: ghost
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
