apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.71.0
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: cse-ghost-data
              mountPath: /var/lib/ghost/content

          env:
            - name: database__client
              value: mysql
            - name: database__connection__host
              value: "10.43.171.121"
            - name: database__connection__user
              value: "alex"
            - name: database__connection__password
              value: "CNiko4zb"
            - name: database__connection__database
              value: "ghostdb"
            - name: database__connection__port
              value: "3306"
            - name: url
              value: "http://192.168.1.216"

      nodeSelector:
        storage: "false"

      volumes:
        - name: cse-ghost-data
          persistentVolumeClaim:
            claimName: cse-ghost-data

---
apiVersion: v1
kind: Service
metadata:
  name: cse-ghost-service
  namespace: ghost-cse
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
  externalIPs:
    - 192.168.1.216
