apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: issuer
 namespace: kube-system
spec:
 acme:
   email: alexbissessur@gmail.com
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: issuer-account-key
   solvers:
     - http01:
         ingress:
           class: traefik
