metadata:
  creationTimestamp: "2024-10-23T19:04:29Z"
  generation: 161738
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:destination:
          .: {}
          f:namespace: {}
          f:server: {}
        f:project: {}
        f:source:
          .: {}
          f:path: {}
          f:repoURL: {}
          f:targetRevision: {}
        f:syncPolicy:
          .: {}
          f:syncOptions: {}
      f:status:
        .: {}
        f:health: {}
        f:sourceHydrator: {}
        f:summary: {}
        f:sync:
          .: {}
          f:comparedTo:
            .: {}
            f:destination: {}
            f:source: {}
    manager: argocd-server
    operation: Update
    time: "2025-08-24T05:39:04Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:controllerNamespace: {}
        f:health:
          f:lastTransitionTime: {}
          f:status: {}
        f:history: {}
        f:operationState:
          .: {}
          f:finishedAt: {}
          f:message: {}
          f:operation:
            .: {}
            f:initiatedBy:
              .: {}
              f:username: {}
            f:retry: {}
            f:sync:
              .: {}
              f:resources: {}
              f:revision: {}
              f:syncOptions: {}
              f:syncStrategy:
                .: {}
                f:hook: {}
          f:phase: {}
          f:startedAt: {}
          f:syncResult:
            .: {}
            f:resources: {}
            f:revision: {}
            f:source:
              .: {}
              f:path: {}
              f:repoURL: {}
              f:targetRevision: {}
        f:reconciledAt: {}
        f:resourceHealthSource: {}
        f:resources: {}
        f:sourceType: {}
        f:summary:
          f:images: {}
        f:sync:
          f:comparedTo:
            f:destination:
              f:namespace: {}
              f:server: {}
            f:source:
              f:path: {}
              f:repoURL: {}
              f:targetRevision: {}
          f:revision: {}
          f:status: {}
    manager: argocd-application-controller
    operation: Update
    time: "2025-09-28T08:22:47Z"
  name: caddy
  namespace: argocd
  resourceVersion: "169777374"
  uid: 80e109f3-b286-4d24-9c36-04a20c0f2ea2
spec:
  destination:
    namespace: caddy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/caddy
    repoURL: https://github.com/xelab04/kates.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-09-28T07:47:32Z"
    status: Healthy
  history:
  - deployStartedAt: "2024-10-23T19:10:16Z"
    deployedAt: "2024-10-23T19:10:17Z"
    id: 0
    initiatedBy:
      username: admin
    revision: 921d2986eda855a37e605e0cdecf480301885c34
    source:
      path: manifests/caddy
      repoURL: https://github.com/xelab04/kates.git
      targetRevision: HEAD
  - deployStartedAt: "2024-10-23T19:31:29Z"
    deployedAt: "2024-10-23T19:31:31Z"
    id: 1
    initiatedBy:
      username: admin
    revision: 92537cf72cfc2b64ac8c72b37b480f32c9f32de0
    source:
      path: manifests/caddy
      repoURL: https://github.com/xelab04/kates.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2025-08-23T18:51:25Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        resources:
        - group: apps
          kind: Deployment
          name: caddy-deployment
          namespace: caddy
        revision: e1c54942765b92e42041952bb03812889b0b9ce3
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2025-08-23T18:51:24Z"
    syncResult:
      resources:
      - group: apps
        hookPhase: Running
        images:
        - caddy:latest
        kind: Deployment
        message: deployment.apps/caddy-deployment created
        name: caddy-deployment
        namespace: caddy
        status: Synced
        syncPhase: Sync
        version: v1
      revision: e1c54942765b92e42041952bb03812889b0b9ce3
      source:
        path: manifests/caddy
        repoURL: https://github.com/xelab04/kates.git
        targetRevision: HEAD
  reconciledAt: "2025-09-28T08:22:47Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: caddy-configmap
    namespace: caddy
    status: OutOfSync
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: caddy-data
    namespace: caddy
    status: OutOfSync
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: caddy-srv
    namespace: caddy
    status: OutOfSync
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: caddy-service
    namespace: caddy
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: caddy-deployment
    namespace: caddy
    status: OutOfSync
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary:
    images:
    - caddy:latest
  sync:
    comparedTo:
      destination:
        namespace: caddy
        server: https://kubernetes.default.svc
      source:
        path: manifests/caddy
        repoURL: https://github.com/xelab04/kates.git
        targetRevision: HEAD
    revision: d6aa3e2c36404c2c78bf3a35c8b933d54074d064
    status: OutOfSync
