metadata:
  name: ghost-website
  namespace: argocd
spec:
  destination:
    namespace: ghost
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/ghost
    repoURL: https://github.com/xelab04/kates.git
    targetRevision: HEAD
