apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default

  sources:
    - repoURL: https://github.com/xelab04/kates.git
      targetRevision: main
      ref: values

    - chart: immich
      repoURL: oci://ghcr.io/immich-app/immich-charts/immich
      targetRevision: 0.9.3
      helm:
        releaseName: immich
        valueFiles:
          - $values/manifests/immich/values.yaml
        ignoreMissingValueFiles: true
