apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-requirements
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/immich/requirements
    repoURL: https://github.com/xelab04/kates.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: false
