metadata:
  name: kraft
  namespace: argocd
spec:
  destination:
    namespace: kraft
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: manifests/
    repoURL: https://github.com/xelab04/KRaft.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
