apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mastodon
  namespace: argocd
spec:
  destination:
    namespace: mastodon
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}

  sources:
    - repoURL: https://github.com/xelab04/kates.git
      targetRevision: main
      ref: values
      
    - repoURL: https://github.com/xelab04/kates.git
      targetRevision: main
      path: manifests/mastodon/requirements

    - chart: app-template
      repoURL: https://bjw-s-labs.github.io/helm-charts/
      targetRevision: 3.7.3
      helm:
        releaseName: app-template
        valueFiles:
          - $values/manifests/mastodon/values.yaml
        ignoreMissingValueFiles: true
