metadata:
  name: meetup-mu-scraper
  namespace: argocd
spec:
  destination:
    namespace: meetup
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/
    repoURL: https://github.com/xelab04/meetup.mu-scraper.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
