apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/xelab04/kates.git
      targetRevision: main
      ref: values

    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 81.4.2
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/manifests/monitoring/values.yaml
        # ignoreMissingValueFiles: true
