apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: app-template
    helm:
      values: |-
        controllers:
          gts:
            replicas: 1
            type: deployment
            containers:
              gts:
                image:
                  repository: docker.io/superseriousbusiness/gotosocial
                  tag: "0.21.2"
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 3.7.3