apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  destination:
    namespace: ollama
    server: https://kubernetes.default.svc
  project: default

  source:
    repoURL: https://github.com/xelab04/kates.git
    targetRevision: main
    path: manifests/ollama
    helm:
      valueFiles:
        - values.yaml

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
