apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  destination:
    namespace: uptime
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/uptimekuma
    repoURL: https://github.com/xelab04/kates.git
    targetRevision: HEAD
