apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  destination:
    namespace: wireguard
    server: https://kubernetes.default.svc
  project: default

  sources:
    - repoURL: https://github.com/xelab04/kates.git
      targetRevision: main
      ref: values

    - chart: wireguard
      repoURL: https://bryopsida.github.io/wireguard-chart
      targetRevision: 0.30.0
      helm:
        releaseName: wireguard
        valueFiles:
          - $values/manifests/wireguard/values.yaml
        ignoreMissingValueFiles: true
