apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: new-longhorn-ui
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.8.0
  name: new-longhorn-ui
  namespace: longhorn-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-longhorn-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: new-longhorn-ui
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/version: v1.8.0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - longhorn-ui
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: LONGHORN_MANAGER_IP
          value: http://longhorn-backend:9500
        - name: LONGHORN_UI_PORT
          value: "8000"
        image: xelab04/longhorn-10817:v1.8.0
        imagePullPolicy: IfNotPresent
        name: new-longhorn-ui
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/cache/nginx/
          name: nginx-cache
        - mountPath: /var/config/nginx/
          name: nginx-config
        - mountPath: /var/run/
          name: var-run
      dnsPolicy: ClusterFirst
      priorityClassName: longhorn-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: longhorn-ui-service-account
      serviceAccountName: longhorn-ui-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: nginx-cache
      - emptyDir: {}
        name: nginx-config
      - emptyDir: {}
        name: var-run
