apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:

      initContainers:
      - name: init-mysql-db
        image: mysql:latest
        command:
          - /bin/sh
          - "-c"
          - |
            echo "Creating databases..."
            mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e "
            CREATE DATABASE IF NOT EXISTS ghost_db;
            CREATE DATABASE IF NOT EXISTS cnmu_db;
            CREATE DATABASE IF NOT EXISTS meetupmu_db;
            "
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: MYSQL_ROOT_PASSWORD

      containers:
        - name: mysql
          image: mysql:latest
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_USER
              value: alex

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghostdbsecrets
                  key: MYSQL_PASSWORD

          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
