apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.59
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: management
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
