# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: phanpyroute
# spec:
#   entryPoints:
#   - websecure
#   - web
#   routes:
#   - kind: Rule
#     match: Host(`phanpy.alexbissessur.dev`)
#     services:
#     - name: anubis-alex
#       port: 3000
#   tls:
#     certResolver: le
