apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gtsroute
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`gts.alexbissessur.dev`)
    services:
    - name: mastodon
      port: 8080
  tls:
    certResolver: le
