# postgresql://username:password@host:port/database
apiVersion: v1
stringData:
  POSTGRES_URL: postgresql://gotosocial:password@main-postgres-rw.cnpg.svc.cluster.local:5432/gotosocial
kind: Secret
metadata:
  name: database-gotosocial-user
